# The URL the site will be built for
base_url = "https://marinecytometry.org"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "papermod"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

[extra.papermod]
title = "Marine Cytometry"
icon = "marcy_logo.svg"
default_theme = "light"
theme = "light"
language_direction = "auto"
keywords = ["cytometry", "flow cytometry", "dark field flow"]
show_theme_toggle = false
show_scroll_to_top = false
show_code_copy_buttons = true
show_reading_time = false
show_word_count = false
show_post_nav_links = false
show_post_meta = true
default_toc_open = false
copyright = "Marine Cytometry Inc."
date_format = "%Y-%m-%d"
navigation = [
    { url = "$BASE_URL/about", title = "About" },
    { url = "$BASE_URL/contact", title = "Contact" }
]

home_title = "Marine Cytometry"
social_icons = [
    #{ url = "https://github.com/alchitry", title = "GitHub", icon = "github" },
    #{ url = "https://youtube.com/c/alchitry", title = "YouTube", icon = "youtube" },
    #{ url = "$BASE_URL/atom.xml", title = "RSS", icon = "rss" },
]